name = "SimpleANOVA"
uuid = "fff527a3-8410-504e-9ca3-60d5e79bb1e4"
authors = ["Nicholas Bauer <nicholasbauer@outlook.com>"]
version = "0.2.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Rmath = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames"]

[compat]
julia = "â‰¥ 1.1"
